#!/bin/bash

#help

if_help=$1
if [[ $if_help == "--help" || $if_help == "-h" ]]; then
        echo "This script install Nginx"
        echo "This script must be rn as root"
        echo "Exit status:" ; echo "0 if OK" ; echo "1 if script runs as not root"; echo "2 if Script has finished working" 
        exit 0
fi

#root check

if [ "$(id -u)" != '0' ]
		then
				echo -e "script runs without root rigths. Try try sudo bash $0"
				exit 1
fi

#Install Apache
yum install -y httpd > /dev/null

#Delete listen 80 port
sed -i 's/'^Listen'/#Listen/' /etc/httpd/conf/httpd.conf

echo "Enter the number of Apache servers"
read var

for (( count=1; count<=$var; count++ ))
        do
				echo "Enter server port"
                read port
                        if [[ $port =~ ^[0-9]{1,5}$ ]]
                                then
                                        echo > /dev/null
                                else
                                        echo -e "Data entry error"
                                        echo "Script has finished working"
                                        exit 2
                        fi

cat << EOF > /etc/httpd/conf.d/for_upstream$count.conf
Listen $port
<VirtualHost *:$port>
#       ServerName www.example.com
#       ServerAdmin webmaster@localhost
DocumentRoot /var/www/html$count
ErrorLog /var/log/httpd/error$count.log
CustomLog /var/log/httpd/access$count.log combined
</VirtualHost>

####################################################
EOF
mkdir /var/www/html$count
cat << EOF > /var/www/html$count/index.html
<h1> Welcome to Apache server on port $port </h1>
EOF

done
		
systemctl enable --now httpd
