#!/bin/bash

#help

if_help=$1
if [[ $if_help == "--help" || $if_help == "-h" ]]; then
        echo "This script backup Mysql databases and send backup to remote server"
		echo "Specify credentials in user@ip, after : specify directory for backup, configure script repetition in cron"
		echo "Don't forget to configure key authentication between servers"
        echo "This script must be run as root"
        echo "Exit status:" ; echo "0 if OK" ; echo "1 if script runs as not root"; echo "2 if data entry error" 
        exit 0
fi

#root check

if [ "$(id -u)" != '0' ]
		then
				echo -e "script runs without root rigths. Try try sudo bash $0"
				exit 1
fi

#Get credentials
echo -e "Enter username from mysql"
read u
echo -e "Enter password from mysql"
read -s p

#Backup
d=$(mysql -u $u -p$p --skip-column-names -e 'show databases')
for t in $d
    do
	if [[ $t == "information_schema"  ||  $t == "mysql"  ||  $t == "performance_schema"  ||  $t == "sys" ]]
		then
			continue
	fi
	a=$(mysql -u $u -p$p --skip-column-names -e "SHOW TABLES FROM $t")
		for dump in $a	
			do
				com=$(mysqldump -u $u -p$p --single-transaction --dump-replica $t $dump > $t'_'$dump.sql )
			done	
    done

tar -rf dump-$(date +%Y-%m-%d.%H-%M-%S).tar *.sql

#Specify credentials in user@ip, after : specify directory for backup, configure script repetition in cron
#Don't forget to configure key authentication between servers
s=$(ls dump-*)
scp -P 22 $s user@ip:/dump

rm *.sql
