#!/bin/bash

#help

if_help=$1
if [[ $if_help == "--help" || $if_help == "-h" ]]; then
        echo "This script install grafana"
        echo "This script must be run as root"
        echo "Exit status:" ; echo "0 if OK" ; echo "1 if script runs as not root"; echo "2 if data entry error" 
        exit 0
fi

#root check

if [ "$(id -u)" != '0' ]
		then
				echo -e "script runs without root rigths. Try try sudo bash $0"
				exit 1
fi

#Download grafana
curl -LO https://dl.grafana.com/oss/release/grafana-9.0.5-1.x86_64.rpm

#Install
yum install -y ./grafana-9.0.5-1.x86_64.rpm > /dev/null

#Start and enable
systemctl enable --now grafana-server.service

#Remove installer
rm -rf grafana-9.0.5-1.x86_64.rpm
