#!/bin/bash

#help

if_help=$1
if [[ $if_help == "--help" || $if_help == "-h" ]]; then
        echo "This script configure Static IP on enp0s3 interface"
        echo "This script must be run as root"
        echo "Exit status:" ; echo "0 if OK" ; echo "1 if script runs as not root"; echo "2 if data entry error" 
        exit 0
fi

#root check

if [ "$(id -u)" != '0' ]
		then
				echo -e "script runs without root rigths. Try try sudo bash $0"
				exit 1
fi

dir=mysqld_exporter-0.14.0.linux-amd64
#Download adn unzip
curl -LO https://github.com/prometheus/mysqld_exporter/releases/download/v0.14.0/mysqld_exporter-0.14.0.linux-amd64.tar.gz
tar -xf mysqld_exporter-0.14.0.linux-amd64.tar.gz
rm mysqld_exporter-0.14.0.linux-amd64.tar.gz

#Create user
useradd --no-create-home --shell /bin/false mysqld_exporter

#Copy files
cp $dir/mysqld_exporter /usr/local/bin/

#Give rights
chown -R mysqld_exporter: /usr/local/bin/mysqld_exporter

#Create file for service
cat << EOF > /etc/systemd/system/mysqld_exporter.service
[Unit]
Description=Mysql Exporter
Wants=network-online.target
After=network-online.target

[Service]
User=mysqld_exporter
Group=mysqld_exporter
Type=simple
ExecStart=/usr/local/bin/mysqld_exporter \
--config.my-cnf /etc/my.cnf.d/mysqld_exporter.cnf

[Install]
WantedBy=multi-user.target
EOF

#Manage mysqld_exporter
echo -e "Enter username from mysql"
read var1
echo -e "Enter password from mysql"
read -s var2

cat<< EOF > /etc/my.cnf.d/mysqld_exporter.cnf

[client]

user=$var1
password=$var2
EOF

#Start and enable mysqld_exporter
systemctl daemon-reload
systemctl enable --now mysqld_exporter.service

#Remove installer
rm -rf $dir
