#!/bin/bash

#help

if_help=$1
if [[ $if_help == "--help" || $if_help == "-h" ]]; then
        echo "This script install Nginx"
        echo "This script must be rn as root"
        echo "Exit status:" ; echo "0 if OK" ; echo "1 if script runs as not root"; echo "2 if Script has finished working" 
        exit 0
fi

#root check

if [ "$(id -u)" != '0' ]
		then
				echo -e "script runs without root rigths. Try try sudo bash $0"
				exit 1
fi

#Установка nginx
yum install -y epel-release >> ~/nginx_installation.log
yum install -y nginx >> ~/nginx_installation.log

#Настройка прокси
cat << EOF > /etc/nginx/default.d/proxy.conf
location / {
        proxy_pass http://backend;
        proxy_set_header Host \$host;
        }
EOF

#Настройка перенаправления потока

cat << EOF > /etc/nginx/conf.d/upstream.conf
upstream backend {
}
EOF


echo "Enter the number of servers to redirect (upstreams)"
read a

for (( count=1; count<=$a; count++ ))
        do
                echo "Enter IP address $count server"
                read a1
                         if [[ $a1 =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]
                                 then
                                        echo > /dev/null
                                 else
                                        echo -e "Data entry error"
                                        echo "Script has finished working"
                                        exit 2
                         fi
                echo "Enter port $count server"
                read a2
                         if [[ $a2 =~ ^[0-9]{1,5}$ ]]
                                 then
                                        echo > /dev/null
                                 else
                                        echo -e "Data entry error"
                                        echo "Script has finished working"
                                        exit 2
                         fi
		echo "Enter priority $count server"
                read a3
                         if [[ $a3 =~ ^[0-9]{1,5}$ ]]
                                 then
                                        echo > /dev/null
                                 else
                                        echo -e "Data entry error"
                                        echo "Script has finished working"
                                        exit 2
                         fi

                sed -i "1a\\\t\\server $a1:$a2 weight=$a3;" /etc/nginx/conf.d/upstream.conf
        done


systemctl enable --now nginx
