#!/bin/bash

#help

if_help=$1
if [[ $if_help == "--help" || $if_help == "-h" ]]; then
        echo "This script install node_exporter"
        echo "This script must be run as root"
        echo "Exit status:" ; echo "0 if OK" ; echo "1 if script runs as not root"; echo "2 if data entry error" 
        exit 0
fi

#root check

if [ "$(id -u)" != '0' ]
		then
				echo -e "script runs without root rigths. Try try sudo bash $0"
				exit 1
fi

dir=node_exporter-1.3.1.linux-amd64
#Download node_exporter
curl -LO https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
tar -xf node_exporter-1.3.1.linux-amd64.tar.gz
rm node_exporter-1.3.1.linux-amd64.tar.gz

#Create user
useradd --no-create-home --shell /bin/false node_exporter

#Copy files
sudo cp $dir/node_exporter /usr/local/bin/

#Give rights
chown -R node_exporter: /usr/local/bin/node_exporter

#Create file for service
cat << EOF > /etc/systemd/system/node_exporter.service
[Unit]
Description=Node Exporter
Wants=network-online.target
After=network-online.target

[Service]
User=node_exporter
Group=node_exporter
Type=simple
ExecStart=/usr/local/bin/node_exporter

[Install]
WantedBy=multi-user.target
EOF

#Start and enable node_exporter
systemctl daemon-reload
systemctl enable --now node_exporter.service

#Remove installer
rm -rf node_exporter-1.3.1.linux-amd64
