#!/bin/bash

#help

if_help=$1
if [[ $if_help == "--help" || $if_help == "-h" ]]; then
        echo "This script install prometheus"
        echo "This script must be rn as root"
        echo "Exit status:" ; echo "0 if OK" ; echo "1 if script runs as not root"; echo "2 if Script has finished working" 
        exit 0
fi

#root check

if [ "$(id -u)" != '0' ]
		then
				echo -e "script runs without root rigths. Try try sudo bash $0"
				exit 1
fi

dir=prometheus-2.37.0.linux-amd64
#Download prometheus
curl -LO https://github.com/prometheus/prometheus/releases/download/v2.37.0/prometheus-2.37.0.linux-amd64.tar.gz > /dev/null
tar -xf prometheus-2.37.0.linux-amd64.tar.gz
rm prometheus-2.37.0.linux-amd64.tar.gz

#Create user
useradd --no-create-home --shell /usr/bin/nologin prometheus

#Create directory
mkdir {/etc/,/var/lib/}prometheus

#Copy files for prometheus
cp -r $dir/consoles $dir/console_libraries $dir/prometheus.yml /etc/prometheus
cp  $dir/prom{etheus,tool} /usr/local/bin/

#Give rights 
chown -R prometheus: /etc/prometheus /var/lib/prometheus /usr/local/bin/prom*


#Create file for service
cat << EOF > /etc/systemd/system/prometheus.service
[Unit]
Description=Prometheus Monitoring
Wants=network-online.target
After=network-online.target

[Service]
User=prometheus
Group=prometheus
Type=simple
ExecStart=/usr/local/bin/prometheus \
--config.file /etc/prometheus/prometheus.yml \
--storage.tsdb.path /var/lib/prometheus/ \
--web.console.templates=/etc/prometheus/consoles \
--web.console.libraries=/etc/prometheus/console_libraries
ExecReload=/bin/kill -HUP $MAINPID

[Install]
WantedBy=multi-user.target
EOF

#Manage prometheus
echo "Enter the number of servers to redirect the data stream to"
read var1

for (( count=1; count<=$var1; count++ ))
        do
		echo "Enter IP address $count server for node_exporter"
		read var2
		        if [[ $var2 =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]
              		then
                        	echo > /dev/null
               		else
                       		echo -e "Data entry error"
                            echo "Script has finished working"
                            exit 2
       			 fi
		numb1[count]=$var2
		echo "Enter IP address $count server for mysql_exporter"
		read var3
        		if [[ $var3 =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]
                	then
                       		echo > /dev/null
                	else
                       		echo -e "Data entry error"
                            echo "Script has finished working"
                            exit 2
        		fi
		numb2[count]=$var3
	done

x1=${numb1[1]}
y1=${numb2[1]}
x2=${numb2[2]}
y2=${numb2[2]}


cat << EOF >> /etc/prometheus/prometheus.yml
  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['$x1:9100', '$x2:9100']
  - job_name: 'mysqld_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['$y1:9104', '$y2:9104']
EOF

#Start and enable prometheus
systemctl daemon-reload
systemctl enable --now prometheus.service

#Remove installer
rm -rf prometheus-2.37.0.linux-amd64
