#!/bin/bash

#help

if_help=$1
if [[ "$if_help" == "--help" || "$if_help" == "-h" ]]; then
        echo "This script disabling firewalld and selinux"
        echo "This script must be run as root"
        echo "Exit status:" ; echo "0 if OK" ; echo "1 if script runs as not root"
        exit 0
fi

#root check

if [ "$(id -u)" != '0' ]
		then
				echo -e "script runs without root rigths. Try try sudo bash $0"
				exit 1
fi

#disabling firewalld

systemctl stop firewalld
systemctl disable firewalld
echo "firewalld stopped and disabled"
systemctl status firewalld
#disabling selinux

setenforce 0
sed -i 's/SELINUX=permissive/SELINUX=disabled/' /etc/selinux/config 
var=$(grep ^SELINUX= /etc/selinux/config)
if [[ $var == "SELINUX=enforcing" ]]; then
        sed -i 's/SELINUX=enforcing/SELINUX=disabled/' /etc/selinux/config
		else
				if [[ $var == "SELINUX=permissive" ]]
						then
						sed -i 's/SELINUX=permissive/SELINUX=disabled/' /etc/selinux/config
				fi
fi
echo "selinux now permissive and disabled in config"
sestatus

exit 0
