#!/bin/bash

#help

if_help=$1
if [[ $if_help == "--help" || $if_help == "-h" ]]; then
        echo "This script configure Static IP on enp0s3 interface"
        echo "This script must be run as root"
        echo "Exit status:" ; echo "0 if OK" ; echo "1 if script runs as not root"; echo "2 if data entry error" 
        exit 0
fi

#root check

if [ "$(id -u)" != '0' ]
		then
				echo -e "script runs without root rigths. Try try sudo bash $0"
				exit 1
fi

#Wanna configure Static IP
echo "Configure Static IP on enp0s3?(Y/N)"
read var1
if [[ $var1 == "Y" || $var1 == "y" ]]
        then
                sed -i 's/BOOTPROTO="dhcp"/BOOTPROTO="static"/' /etc/sysconfig/network-scripts/ifcfg-enp0s3
        else
                echo "Script has finished working"
                exit 0
fi
#Enter IP address
echo "Enter IP address"
read addr
	if [[ $addr =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]
		then
                        if  [[ $(grep 'IPADDR' /etc/sysconfig/network-scripts/ifcfg-enp0s3) =~ ^IPADDR ]]
                                then
                                        sed -i -r "s/IPADDR=([0-9]{1,3}\.){3}[0-9]{1,3}/IPADDR=$addr/" /etc/sysconfig/network-scripts/ifcfg-enp0s3
                                else
                                        sed -i "a\\IPADDR=$addr" /etc/sysconfig/network-scripts/ifcfg-enp0s3
                        fi
                else
                        echo -e "Data entry error"
                        echo "Script has finished working"
                        exit 2

        fi

#Enter subnet
echo "Enter subnet in the format 0.0.0.0"
read netmask
	if [[ $netmask =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]
		then
                        if  [[ $(grep 'NETMASK' /etc/sysconfig/network-scripts/ifcfg-enp0s3) =~ ^NETMASK ]]
                                then
                                        sed -i -r "s/NETMASK=([0-9]{1,3}\.){3}[0-9]{1,3}/NETMASK=$netmask/" /etc/sysconfig/network-scripts/ifcfg-enp0s3
                                else
                                        sed -i "a\\NETMASK=$netmask" /etc/sysconfig/network-scripts/ifcfg-enp0s3
                        fi
                else
                        echo -e "Data entry error"
                        echo "Script has finished working"
                        exit 2

        fi
#Enter gateway
echo "Enter gateway"
read gw
        if [[ $gw =~ ^([0-9]{1,3}\.){3}[1-9]{1,3}$ ]]
                then
			if  [[ $(grep 'GATEWAY' /etc/sysconfig/network-scripts/ifcfg-enp0s3) =~ ^GATEWAY ]]
				then
					sed -i -r "s/GATEWAY=([0-9]{1,3}\.){3}[0-9]{1,3}/GATEWAY=$gw/" /etc/sysconfig/network-scripts/ifcfg-enp0s3
				else
                       			 sed -i "a\\GATEWAY=$gw" /etc/sysconfig/network-scripts/ifcfg-enp0s3
			fi
		else
                        echo -e "Data entry error"
                        echo "Script has finished working"
                        exit 2
        fi
#Enter DNS
echo "Enter DNS1"
read dns1
        if [[ $dns1 =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]
                then
                        if  [[ $(grep 'DNS1' /etc/sysconfig/network-scripts/ifcfg-enp0s3) =~ ^DNS1 ]]
                                then
                                        sed -i -r "s/DNS1=([0-9]{1,3}\.){3}[0-9]{1,3}/DNS1=$dns1/" /etc/sysconfig/network-scripts/ifcfg-enp0s3
                                else
                                         sed -i "a\\DNS1=$dns1" /etc/sysconfig/network-scripts/ifcfg-enp0s3
                        fi
                else
                        echo -e "Data entry error"
                        echo "Script has finished working"
                        exit 2
        fi

echo "Enter DNS2"
read dns2
        if [[ $dns2 =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]
                then
                        if  [[ $(grep 'DNS2' /etc/sysconfig/network-scripts/ifcfg-enp0s3) =~ ^DNS2 ]]
                                then
                                        sed -i -r "s/DNS2=([0-9]{1,3}\.){3}[0-9]{1,3}/DNS2=$dns2/" /etc/sysconfig/network-scripts/ifcfg-enp0s3
                                else
                                         sed -i "a\\DNS2=$dns2" /etc/sysconfig/network-scripts/ifcfg-enp0s3
                        fi
                else
                        echo -e "Data entry error"
                        echo "Script has finished working"
                        exit 2
        fi

systemctl restart network
